(() => {
 const $ = id => document.getElementById(id);
 const config = window.SITE_CONFIG || {};
 const site = 'https://filipe01000.github.io/servicos-ti/';
 const phone = /^\d{10,15}$/.test(config.whatsapp || '') ? config.whatsapp : '5571992984439';
 const wa = text => `https://wa.me/${phone}?text=${encodeURIComponent(text)}`;
 const read = key => { try { return JSON.parse(window.SITE_STORAGE.getItem(key)); } catch (_) { return null; } };
 const save = (key,value) => { try { window.SITE_STORAGE.setItem(key,JSON.stringify(value)); } catch (_) {} };
 const download = (name,text) => { const url = URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000); };
 async function share(text,url,status) {
   try { if(navigator.share) { await navigator.share({title:'Filipe Augusto TI',text,url});status.textContent=''; }
   else if(navigator.clipboard && window.isSecureContext) { await navigator.clipboard.writeText(text+'\n'+url);status.textContent='Copiado! Cole na conversa ou publicação.'; }
   else { status.textContent=text+' '+url; } } catch(error) { status.textContent=error.name==='AbortError'?'Compartilhamento cancelado.':'Não foi possível compartilhar automaticamente. Copie este link: '+url; }
 }
 $('triage').addEventListener('submit',event=>{
   event.preventDefault();
   const tips={slow:'Observe se a lentidão ocorre em um programa ou em todo o computador. Verifique o espaço livre e os aplicativos iniciados junto com o sistema. Evite instalar otimizadores desconhecidos.',wifi:'Compare a conexão perto e longe do roteador e veja se o problema afeta outros aparelhos. Isso ajuda a diferenciar sinal fraco de um problema geral. Não restaure o roteador às configurações de fábrica sem ter os dados de configuração.',files:'Evite gravar novos dados no dispositivo afetado. Confira a lixeira e cópias de backup. Se os arquivos forem importantes, procure avaliação antes de instalar ferramentas de recuperação no mesmo disco.',power:'Confira a tomada e as conexões externas de energia. Não abra a fonte de alimentação. Se não houver uma causa externa evidente, peça uma avaliação.'};
   let text=$('danger').checked?'Interrompa o uso. Se for seguro, desconecte o equipamento da energia. Não tente ligar novamente nem abrir a fonte; procure avaliação técnica.':tips[$('problem').value];
   if($('recent').value==='yes'&&!$('danger').checked)text+='\n\nAnote qual mudança foi feita e quando o problema começou para informar no atendimento.';
   $('triage-result').textContent=text;$('triage-result').hidden=false;
   $('triage-contact').href=wa('Olá, Filipe. Fiz a triagem do site.\nProblema: '+$('problem').selectedOptions[0].textContent+'\nMudança recente: '+$('recent').selectedOptions[0].textContent+'\nCheiro de queimado, líquido ou aquecimento incomum: '+($('danger').checked?'Sim':'Não')+'\nGostaria de uma avaliação.');$('triage-contact').hidden=false;
 });
 $('backup').addEventListener('submit',e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;const total=Number($('gb').value)*Number($('copies').value)*(1+Number($('growth').value)/100);$('backup-result').textContent='Estimativa: '+total.toLocaleString('pt-BR',{maximumFractionDigits:2})+' GB para as cópias completas ('+(total/1000).toLocaleString('pt-BR',{maximumFractionDigits:2})+' TB decimais).';});
 $('network').addEventListener('submit',e=>{e.preventDefault();if(!e.currentTarget.reportValidity())return;$('network-result').textContent='Planeje '+(Number($('devices').value)+Number($('spare').value)).toLocaleString('pt-BR')+' pontos de rede. Avalie portas adicionais para interligar os equipamentos de rede.';});
 const checks=['Tenho backup dos arquivos importantes.','Testei a restauração de uma cópia de backup.','Mantenho sistema e aplicativos atualizados.','Ativei autenticação multifator nas contas que permitem.','Uso senhas únicas e um gerenciador de senhas.','Revisei quem tem acesso aos arquivos e sistemas.','Tenho uma lista dos equipamentos e suas necessidades.','Sei quem contatar em caso de falha.'];
 const stored=read('fa-check-v1');let marks=Array.isArray(stored)?checks.map((_,i)=>stored[i]===true):checks.map(()=>false);
 function updateChecks(){save('fa-check-v1',marks);$('check-result').textContent=marks.filter(Boolean).length+' de '+checks.length+' cuidados verificados.';}
 checks.forEach((text,i)=>{const label=document.createElement('label');label.className='check';const input=document.createElement('input');input.type='checkbox';input.checked=marks[i];input.addEventListener('change',()=>{marks[i]=input.checked;updateChecks();});label.append(input,document.createTextNode(text));$('checks').append(label);});updateChecks();
 $('reset-check').onclick=()=>{marks=checks.map(()=>false);$('checks').querySelectorAll('input').forEach(input=>input.checked=false);updateChecks();};
 $('download-check').onclick=()=>download('meu-checklist-ti.txt','Checklist de TI — Filipe Augusto\n\n'+checks.map((text,i)=>(marks[i]?'[Verificado] ':'[Pendente] ')+text).join('\n')+'\n\nResumo de organização pessoal; não é auditoria de segurança.');
 const questions=[
 {q:'Uma aplicação precisa apenas ler arquivos de um local específico. Qual acesso conceder?',a:['Administrador de toda a conta','Somente leitura no recurso necessário','A mesma conta usada por todos os funcionários'],correct:1,why:'O menor privilégio limita ações e recursos ao necessário. Isso reduz o impacto de um erro ou comprometimento.'},
 {q:'Você vai publicar um projeto no GitHub. Onde deve ficar a chave secreta de acesso à nuvem?',a:['No JavaScript, com o nome disfarçado','Em um comentário no HTML','Fora do código público, em um serviço seguro no servidor'],correct:2,why:'Arquivos enviados ao navegador podem ser inspecionados. Segredos exigem armazenamento e uso protegidos fora do código público; quando possível, use credenciais temporárias.'},
 {q:'Uma conta administrativa ainda usa apenas senha. Qual medida adiciona proteção?',a:['Ativar autenticação multifator','Trocar o nome da conta','Esconder o link de login'],correct:0,why:'MFA exige um fator adicional de autenticação. Prefira métodos resistentes a phishing quando disponíveis; MFA não elimina todos os riscos.'},
 {q:'O backup terminou sem erro. Como verificar se ele atende à recuperação?',a:['Considerar o trabalho encerrado','Apagar o original para testar','Testar a restauração em um local separado e controlado'],correct:2,why:'Um teste de restauração verifica se os dados podem ser recuperados. Preserve os originais e confirme também se os prazos de recuperação são adequados.'}
 ];
 let responses={};function score(){const done=Object.keys(responses).length;const right=questions.filter((q,i)=>responses[i]===q.correct).length;return{done,right,text:`${right} acerto(s) em ${done} desafio(s) respondido(s), de ${questions.length}.`};}
 function renderQuiz(){ $('quiz').replaceChildren();questions.forEach((q,i)=>{const section=document.createElement('div');section.className='question';const field=document.createElement('fieldset');const legend=document.createElement('legend');legend.textContent=(i+1)+'. '+q.q;field.append(legend);q.a.forEach((answer,j)=>{const button=document.createElement('button');button.type='button';button.className='answer';button.textContent=answer;button.onclick=()=>{responses[i]=j;field.querySelectorAll('button').forEach((b,k)=>{b.disabled=true;if(k===j)b.classList.add('selected');});const explanation=document.createElement('p');explanation.className='explanation';explanation.setAttribute('role','status');explanation.textContent=(j===q.correct?'Correto. ':'Resposta correta: '+q.a[q.correct]+'. ')+q.why;section.append(explanation);$('quiz-score').textContent=score().text;};field.append(button);});section.append(field);$('quiz').append(section);});$('quiz-score').textContent='Responda aos 4 desafios para testar seus conhecimentos.';}
 renderQuiz();$('reset-quiz').onclick=()=>{responses={};renderQuiz();$('share-status').textContent='';};$('share-quiz').onclick=()=>{if(score().done!==questions.length){$('share-status').textContent='Responda aos quatro desafios antes de compartilhar.';return;}share('Fiz os desafios de segurança na nuvem: '+score().text+' Aprendendo todos os dias!',site+'recursos.html#aprender',$('share-status'));};
 const articles=[
 ['Redes','Wi-Fi e internet são coisas diferentes','O Wi-Fi conecta seu aparelho à rede local. A conexão com a internet pode falhar mesmo quando o sinal de Wi-Fi está forte. Compare outros aparelhos e a conexão por cabo para reunir pistas.'],
 ['Hardware','SSD e RAM: funções diferentes','O SSD armazena arquivos e programas. A RAM mantém dados em uso durante a execução. O upgrade adequado depende do uso, do diagnóstico e da compatibilidade do equipamento.'],
 ['Segurança','Backup precisa de teste','Ter uma cópia é o começo. Teste a restauração em um local separado, preserve os originais e mantenha cópias protegidas contra acesso indevido.','https://www.cisa.gov/stopransomware/ransomware-guide'],
 ['Cloud','Permissão suficiente, sem excesso','O princípio do menor privilégio concede apenas as ações e os recursos necessários. Revise os acessos conforme as responsabilidades mudam.','https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html'],
 ['Segurança','Uma camada a mais no acesso','Ative MFA sempre que possível. Uma senha vazada não deve ser a única barreira entre uma pessoa mal-intencionada e sua conta.','https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html'],
 ['Cloud','Código público não guarda segredos','Não coloque chaves secretas em JavaScript entregue ao navegador. O visitante pode inspecionar esses arquivos. Use uma arquitetura que mantenha os segredos fora do cliente.','https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html']
 ];
 const norm=t=>t.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();function library(){const query=norm($('search').value);const filtered=articles.filter(a=>(!$('category').value||a[0]===$('category').value)&&norm(a.slice(0,3).join(' ')).includes(query));$('library').replaceChildren();filtered.forEach(a=>{const article=document.createElement('article');article.className='library-card';const tag=document.createElement('span');tag.textContent=a[0];const h=document.createElement('h3');h.textContent=a[1];const p=document.createElement('p');p.textContent=a[2];article.append(tag,h,p);if(a[3]){const link=document.createElement('a');link.href=a[3];link.textContent='Consultar referência ↗';link.target='_blank';link.rel='noopener noreferrer';article.append(link);}$('library').append(article);});$('library-count').textContent=filtered.length?filtered.length+' texto(s) para você consultar.':'Nenhum guia encontrado. Tente outro termo.';}
 $('search').oninput=library;$('category').onchange=library;library();
 const safeUrl=value=>{try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:null;}catch(_){return null;}};
 (Array.isArray(config.portfolio)?config.portfolio:[]).forEach(work=>{if(!work.title||!work.description)return;const article=document.createElement('article');article.className='library-card';const h=document.createElement('h3');h.textContent=work.title;const p=document.createElement('p');p.textContent=work.description;article.append(h,p);const pair=document.createElement('div');pair.className='work-pair';[['Antes',work.before],['Depois',work.after]].forEach(([label,path])=>{if(typeof path!=='string'||!/^assets\/[a-zA-Z0-9/_-]+\.(png|jpg|jpeg|webp)$/i.test(path))return;const figure=document.createElement('figure');const img=document.createElement('img');img.src=path;img.alt=label+' — '+work.title;img.loading='lazy';const caption=document.createElement('figcaption');caption.textContent=label;figure.append(img,caption);pair.append(figure);});article.append(pair);$('work-list').append(article);$('work-empty').hidden=true;});
 $('booking').href=wa('Olá, Filipe. Gostaria de consultar a disponibilidade para um atendimento.');
 const booking=safeUrl(config.bookingUrl);if(booking){$('booking').href=booking;$('booking').textContent='Marcar conversa de 15 min ↗';$('booking-note').textContent='Escolha um horário para uma conversa de 15 minutos. É para entender o problema; o serviço será combinado depois. Confira na agenda como será a conversa.';}
 const portal=safeUrl(config.clientPortalUrl);if(portal){$('portal').href=portal;$('portal').hidden=false;$('portal-note').textContent='Abra o portal e entre na sua conta para ver seu atendimento.';}
 $('share-site').onclick=()=>share('Filipe Augusto — Serviços de TI',site,$('contact-status'));
 const qrFrame=document.createElement('div');qrFrame.className='qr-frame';const qrLogo=document.createElement('img');qrLogo.src='assets/logo.png';qrLogo.alt='';qrLogo.className='qr-logo';qrLogo.hidden=true;const qr=document.createElement('img');qr.className='qr-code';qr.alt='QR code para abrir o site de Filipe Augusto';qr.width=180;qr.height=180;qr.loading='lazy';qr.referrerPolicy='no-referrer';qr.src='https://api.qrserver.com/v1/create-qr-code/?size=480x480&ecc=H&qzone=4&data='+encodeURIComponent(site);qr.onload=()=>{qrLogo.hidden=false;$('qr-note').textContent='Aponte a câmera do celular para abrir o site.';};qr.onerror=()=>{qrFrame.hidden=true;$('qr-note').textContent='O QR code não carregou. Você pode usar o botão Compartilhar site.';};qrLogo.onerror=()=>{qrLogo.hidden=true;};qrFrame.append(qr,qrLogo);$('qr').append(qrFrame);
})();

